In [8]:
import pickle
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import datetime 
import seaborn as sns
from scipy import stats
import xarray as xr
from importlib import reload 
import torch
from transformers import *
from neural_nlp.benchmarks.neural import *
from neural_nlp.models import *
import neural_nlp
from neural_nlp.models.implementations import *
from neural_nlp.stimuli import StimulusSet
from pathlib import Path
import os

# Plot specifications
sns.set(context='talk')
sns.set_style("whitegrid", {'axes.grid': False})
plt.rc('axes', edgecolor='black')
plt.rc('axes', edgecolor='black')
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.spines.top'] = False

score_name1 = '/Users/gt/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding-weights,model=distilgpt2,subsample=None,oneweight.pkl'
score_name = '/Users/gt/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding-weights,model=distilgpt2,subsample=None.pkl'

In [9]:
# Load score objects
with open(score_name1, 'rb') as f:  
    result1 = pickle.load(f)

score1 = result1['data']

with open(score_name, 'rb') as f:  
    result = pickle.load(f)

score = result['data']

In [10]:
score

<xarray.Score (layer: 7, aggregation: 2)>
array([[-0.023974,  0.097927],
       [ 0.143942,  0.125787],
       [ 0.273343,  0.187895],
       [ 0.384026,  0.088253],
       [ 0.369323,  0.224276],
       [ 0.261079,  0.274317],
       [ 0.177751,  0.099441]])
Coordinates:
  * layer        (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:            <xarray.Score (layer: 7, neuroid: 97)>\narray([[ 0.248347...
    description:    per-neuroid ceiling-normalized score
    ceiling:        <xarray.Score (aggregation: 3)>\narray([0.168649, 0.05278...
    weights:        <xarray.NeuroidAssembly (neuroid_id: 97, neuroid: 768)>\n...
    model:          distilgpt2
    benchmark:      Fedorenko2016v3-encoding-weights
    layer_weights:  [<xarray.NeuroidAssembly (neuroid_id: 97, neuroid: 768)>\...

In [11]:
score1

<xarray.Score (layer: 7, aggregation: 2)>
array([[-0.023974,  0.097927],
       [ 0.143942,  0.125787],
       [ 0.273343,  0.187895],
       [ 0.384026,  0.088253],
       [ 0.369323,  0.224276],
       [ 0.261079,  0.274317],
       [ 0.177751,  0.099441]])
Coordinates:
  * layer        (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (layer: 7, neuroid: 97)>\narray([[ 0.248347, ...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.168649, 0.052784,...
    weights:      <xarray.NeuroidAssembly (neuroid_id: 97, neuroid: 768)>\nar...
    model:        distilgpt2
    benchmark:    Fedorenko2016v3-encoding-weights

In [13]:
score.layer_weights

[<xarray.NeuroidAssembly (neuroid_id: 97, neuroid: 768)>
 array([[ 53820.008  ,   4611.564  ,   1355.1372 , ...,  -1664.9479 ,
          -1191.4778 ,    781.6066 ],
        [-46355.137  ,  -3973.1907 ,  -1168.7916 , ...,   1433.8142 ,
           1030.6385 ,   -671.6611 ],
        [ 46743.043  ,   4005.611  ,   1176.9724 , ...,  -1446.4127 ,
          -1036.7222 ,    678.9757 ],
        ...,
        [ 79729.86   ,   6832.5425 ,   2009.2396 , ...,  -2466.6238 ,
          -1772.9968 ,   1156.3755 ],
        [101940.68   ,   8734.581  ,   2567.9712 , ...,  -3153.5269 ,
          -2261.819  ,   1479.3164 ],
        [ 27030.31   ,   2316.4827 ,    680.953  , ...,   -836.29266,
           -601.7634 ,    392.30695]], dtype=float32)
 Coordinates:
   * neuroid     (neuroid) object (0, 'distilgpt2', 'drop', 'distilgpt2.drop.0') ... (767, 'distilgpt2', 'drop', 'distilgpt2.drop.767')
   * neuroid_id  (neuroid_id) int64 0 1 2 3 4 5 6 7 8 ... 89 90 91 92 93 94 95 96
 Attributes:
     intercept:  <xar

In [12]:
score1.weights

<xarray.NeuroidAssembly (neuroid_id: 97, neuroid: 768)>
array([[-516.02814 ,  -32.954746,  -25.71829 , ...,  -27.29274 ,   41.847992,
         -16.529102],
       [ 678.4166  ,   43.232765,   33.49083 , ...,   36.32059 ,  -55.562138,
          21.166988],
       [ -74.500565,   -4.505579,   -3.610722, ...,   -3.742369,    5.546775,
          -2.454091],
       ...,
       [  54.091255,    3.050629,    2.679733, ...,    2.944711,   -4.753502,
           1.550281],
       [ -96.87034 ,   -6.48741 ,   -4.833493, ...,   -5.1001  ,    7.472761,
          -3.344016],
       [ 340.97964 ,   21.363941,   16.942305, ...,   18.57168 ,  -27.591982,
          10.848014]], dtype=float32)
Coordinates:
  * neuroid     (neuroid) object (0, 'distilgpt2', 'encoder.h.5', 'distilgpt2.encoder.h.5.0') ... (767, 'distilgpt2', 'encoder.h.5', 'distilgpt2.encoder.h.5.767')
  * neuroid_id  (neuroid_id) int64 0 1 2 3 4 5 6 7 8 ... 89 90 91 92 93 94 95 96
Attributes:
    intercept:  <xarray.NeuroidAssembly (neuroi

In [6]:
score.attrs.keys()


odict_keys(['raw', 'description', 'ceiling', 'weights', 'model', 'benchmark'])