In [3]:
import os
import numpy as np
import pickle
import pandas as pd

In [4]:
filepath = '/om2/user/ckauf/.result_caching/neural_nlp.score/'
filename = 'benchmark=Pereira2018-encoding-ablation-nouns,model=distilgpt2,subsample=None.pkl'

with open(os.path.join(filepath,filename), 'rb') as f:
    score = pickle.load(f)
score

{'data': <xarray.Score (layer: 7, aggregation: 2)>
 array([[0.027873, 0.056556],
        [0.301125, 0.112333],
        [0.339348, 0.132698],
        [0.326258, 0.112573],
        [0.355289, 0.140901],
        [0.474327, 0.122303],
        [0.626163, 0.161234]])
 Coordinates:
   * layer        (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
   * aggregation  (aggregation) <U6 'center' 'error'
 Attributes:
     raw:          <xarray.Score (layer: 7, aggregation: 2)>\narray([[0.008879...
     ceiling:      <xarray.Score (aggregation: 3)>\narray([0.318567, 0.012958,...
     description:  ceiling-normalized score
     model:        distilgpt2
     benchmark:    Pereira2018-encoding-ablation-nouns}

In [5]:
filename = 'benchmark=Pereira2018-encoding-scrambled-original,model=distilgpt2,subsample=None.pkl'

with open(os.path.join(filepath,filename), 'rb') as f:
    score = pickle.load(f)
score

{'data': <xarray.Score (layer: 7, aggregation: 2)>
 array([[0.017986, 0.053266],
        [0.242382, 0.098416],
        [0.223671, 0.126549],
        [0.261688, 0.150214],
        [0.278405, 0.175883],
        [0.37947 , 0.163328],
        [0.445486, 0.141692]])
 Coordinates:
   * layer        (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
   * aggregation  (aggregation) <U6 'center' 'error'
 Attributes:
     raw:          <xarray.Score (layer: 7, aggregation: 2)>\narray([[0.00573 ...
     ceiling:      <xarray.Score (aggregation: 3)>\narray([0.318567, 0.012958,...
     description:  ceiling-normalized score
     model:        distilgpt2
     benchmark:    Pereira2018-encoding-scrambled-original}

In [6]:

filename = 'benchmark=Pereira2018-encoding,model=distilgpt2,subsample=None.pkl'

with open(os.path.join(filepath,filename), 'rb') as f:
    score = pickle.load(f)
score

{'data': <xarray.Score (layer: 7, aggregation: 2)>
 array([[0.016583, 0.085925],
        [0.548441, 0.063597],
        [0.615049, 0.135957],
        [0.548156, 0.1102  ],
        [0.677802, 0.16454 ],
        [0.834165, 0.113426],
        [0.927702, 0.115135]])
 Coordinates:
   * layer        (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
   * aggregation  (aggregation) <U6 'center' 'error'
 Attributes:
     raw:          <xarray.Score (layer: 7, aggregation: 2)>\narray([[0.005283...
     ceiling:      <xarray.Score (aggregation: 3)>\narray([0.318567, 0.012958,...
     description:  ceiling-normalized score
     model:        distilgpt2
     benchmark:    Pereira2018-encoding}